2024-04-18 18:06:52,131: WARNING	werkzeug:	Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.
2024-04-18 23:39:06,458: ERROR	pgadmin:	'TableCommand' object has no attribute 'conn_id_ac'
2024-04-18 23:39:06,461: ERROR	pgadmin:	'TableCommand' object has no attribute 'conn_id_ac'
2024-04-18 23:39:06,469: ERROR	pgadmin:	'TableCommand' object has no attribute 'conn_id_ac'
2024-04-18 23:45:15,923: WARNING	werkzeug:	Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.
2024-04-19 08:38:14,553: WARNING	werkzeug:	Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.
2024-04-19 12:29:13,559: ERROR	pgadmin:	Failed to execute query (execute_scalar) for the server #1 - DB:Netflix (Query-id: 7053380):
Error Message:there is no unique constraint matching given keys for referenced table "Director"
2024-04-19 12:30:39,316: ERROR	pgadmin:	Failed to execute query (execute_scalar) for the server #1 - DB:Netflix (Query-id: 3788032):
Error Message:there is no unique constraint matching given keys for referenced table "Content"
2024-04-19 13:17:39,988: WARNING	werkzeug:	Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.
2024-04-19 13:22:52,705: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:277582(Query-id: 8990756):
Error Message:ERROR:  syntax error at or near "director"
LINE 4:  director varchar (100),
         ^ 

SQL state: 42601
Character: 68
2024-04-19 13:25:03,210: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:277582(Query-id: 449338):
Error Message:ERROR:  syntax error at or near "director"
LINE 4:  director varchar(100),
         ^ 

SQL state: 42601
Character: 68
2024-04-19 13:25:09,005: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:277582(Query-id: 6103490):
Error Message:ERROR:  syntax error at or near "Foreign"
LINE 7:  Foreign key (director) References Director(Director_Name) 
         ^ 

SQL state: 42601
Character: 169
2024-04-19 13:25:17,588: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:277582(Query-id: 6268805):
Error Message:ERROR:  relation "content" does not exist 

SQL state: 42P01
2024-04-19 13:26:07,922: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:277582(Query-id: 8750136):
Error Message:ERROR:  relation "content" does not exist 

SQL state: 42P01
2024-04-19 13:26:13,540: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:277582(Query-id: 6752150):
Error Message:ERROR:  relation "content" does not exist 

SQL state: 42P01
2024-04-19 13:27:03,475: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:277582(Query-id: 4693648):
Error Message:ERROR:  syntax error at or near "Content"
LINE 1: Content
        ^ 

SQL state: 42601
Character: 1
2024-04-19 13:28:22,920: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:277582(Query-id: 7809391):
Error Message:ERROR:  relation "content" does not exist 

SQL state: 42P01
2024-04-19 13:28:41,043: ERROR	pgadmin:	'TableCommand' object has no attribute 'conn_id_ac'
2024-04-19 13:30:15,958: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:277582(Query-id: 9369121):
Error Message:ERROR:  relation "content" does not exist 

SQL state: 42P01
2024-04-19 13:30:27,598: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:277582(Query-id: 6155413):
Error Message:ERROR:  relation "content" does not exist 

SQL state: 42P01
2024-04-19 13:31:39,599: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:277582(Query-id: 9061320):
Error Message:ERROR:  relation "content" does not exist 

SQL state: 42P01
2024-04-19 13:34:49,412: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:277582(Query-id: 7568082):
Error Message:ERROR:  relation "public.content" does not exist 

SQL state: 42P01
2024-04-19 13:34:58,062: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:277582(Query-id: 6549059):
Error Message:ERROR:  relation "content" does not exist 

SQL state: 42P01
2024-04-19 13:35:35,136: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:277582(Query-id: 5738213):
Error Message:ERROR:  syntax error at or near "\"
LINE 1: \dp Content
        ^ 

SQL state: 42601
Character: 1
2024-04-19 13:42:00,048: ERROR	pgadmin:	Failed to execute query (execute_scalar) for the server #1 - DB:Netflix (Query-id: 4012377):
Error Message:there is no unique constraint matching given keys for referenced table "Content"
2024-04-19 13:43:30,570: ERROR	pgadmin:	Failed to execute query (execute_scalar) for the server #1 - DB:Netflix (Query-id: 6866705):
Error Message:there is no unique constraint matching given keys for referenced table "Content"
2024-04-19 13:45:06,199: ERROR	pgadmin:	Failed to execute query (execute_scalar) for the server #1 - DB:Netflix (Query-id: 1640390):
Error Message:there is no unique constraint matching given keys for referenced table "Content"
2024-04-19 13:52:14,874: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:1241485(Query-id: 549945):
Error Message:ERROR:  relation "director" does not exist 

SQL state: 42P01
2024-04-19 13:59:13,309: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:1241485(Query-id: 1382803):
Error Message:ERROR:  relation "director" does not exist 

SQL state: 42P01
2024-04-19 14:08:36,388: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:1241485(Query-id: 8945915):
Error Message:ERROR:  syntax error at or near "SERIAL"
LINE 1: SERIAL
        ^ 

SQL state: 42601
Character: 1
2024-04-19 14:10:39,055: ERROR	pgadmin:	Failed to execute query (execute_scalar) for the server #1 - DB:Netflix (Query-id: 1178597):
Error Message:there is no unique constraint matching given keys for referenced table "Content"
2024-04-19 14:10:46,342: ERROR	pgadmin:	Failed to execute query (execute_scalar) for the server #1 - DB:Netflix (Query-id: 3528473):
Error Message:there is no unique constraint matching given keys for referenced table "Content"
2024-04-19 14:11:54,816: ERROR	pgadmin:	Failed to execute query (execute_scalar) for the server #1 - DB:Netflix (Query-id: 5747365):
Error Message:there is no unique constraint matching given keys for referenced table "Director"
2024-04-19 14:23:02,400: ERROR	pgadmin:	Failed to execute query (execute_scalar) for the server #1 - DB:Netflix (Query-id: 2686324):
Error Message:Table "Directed_By" references "Director".cannot truncate a table referenced in a foreign key constraint
2024-04-19 14:24:15,439: ERROR	pgadmin:	Failed to execute query (execute_scalar) for the server #1 - DB:Netflix (Query-id: 6058938):
Error Message:Table "Directed_By" references "Director".cannot truncate a table referenced in a foreign key constraint
2024-04-19 14:38:28,358: ERROR	pgadmin:	Failed to execute query (execute_scalar) for the server #1 - DB:Netflix (Query-id: 184644):
Error Message:Table "Directed_By" references "Director".cannot truncate a table referenced in a foreign key constraint
2024-04-19 15:19:42,754: ERROR	pgadmin:	'TableCommand' object has no attribute 'conn_id_ac'
2024-04-19 18:54:36,023: ERROR	pgadmin:	Failed to execute query (execute_scalar) for the server #1 - DB:Netflix (Query-id: 5299586):
Error Message:Table "Casted_With" references "Cast".cannot truncate a table referenced in a foreign key constraint
2024-04-19 18:56:27,938: ERROR	pgadmin:	Failed to execute query (execute_scalar) for the server #1 - DB:Netflix (Query-id: 2519074):
Error Message:Table "Casted_With" references "Cast".cannot truncate a table referenced in a foreign key constraint
2024-04-19 20:12:00,149: ERROR	pgadmin:	Failed to execute query (execute_dict) for the server #1- CONN:3302037 (Query-id: 6334497):
Error Message:Key (cast_id)=(698) already exists.duplicate key value violates unique constraint "Cast_pkey"
2024-04-19 20:12:03,209: ERROR	pgadmin:	Failed to execute query (execute_dict) for the server #1- CONN:3302037 (Query-id: 5250743):
Error Message:Key (cast_id)=(698) already exists.duplicate key value violates unique constraint "Cast_pkey"
2024-04-19 20:15:12,844: ERROR	pgadmin:	'TableCommand' object has no attribute 'conn_id_ac'
2024-04-19 20:25:57,744: ERROR	pgadmin:	Failed to execute query (execute_scalar) for the server #1 - DB:Netflix (Query-id: 8594842):
Error Message:there is no unique constraint matching given keys for referenced table "Location"
2024-04-19 20:31:58,303: ERROR	pgadmin:	'TableCommand' object has no attribute 'conn_id_ac'
2024-04-19 20:31:59,578: ERROR	pgadmin:	'TableCommand' object has no attribute 'conn_id_ac'
2024-04-19 20:32:03,822: ERROR	pgadmin:	'TableCommand' object has no attribute 'conn_id_ac'
2024-04-19 20:32:05,973: ERROR	pgadmin:	'TableCommand' object has no attribute 'conn_id_ac'
2024-04-19 20:32:07,220: ERROR	pgadmin:	'TableCommand' object has no attribute 'conn_id_ac'
